//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MushROMs.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value &quot;{0}&quot; is not recognized as an extension..
        /// </summary>
        internal static string ErrorBadExtension {
            get {
                return ResourceManager.GetString("ErrorBadExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The editor initialize method returned a null value..
        /// </summary>
        internal static string ErrorEditorInitialization {
            get {
                return ResourceManager.GetString("ErrorEditorInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified editor is not included in the master editor..
        /// </summary>
        internal static string ErrorEditorNotFound {
            get {
                return ResourceManager.GetString("ErrorEditorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is not a valid or recognized Editor Type..
        /// </summary>
        internal static string ErrorEditorType {
            get {
                return ResourceManager.GetString("ErrorEditorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension &quot;{0}&quot; is not supported or recognized..
        /// </summary>
        internal static string ErrorInvalidExtension {
            get {
                return ResourceManager.GetString("ErrorInvalidExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No copy data exists..
        /// </summary>
        internal static string ErrorNoCopyData {
            get {
                return ResourceManager.GetString("ErrorNoCopyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing left to redo..
        /// </summary>
        internal static string ErrorNoRedoData {
            get {
                return ResourceManager.GetString("ErrorNoRedoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No selection exists..
        /// </summary>
        internal static string ErrorNoSelection {
            get {
                return ResourceManager.GetString("ErrorNoSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing left to undo..
        /// </summary>
        internal static string ErrorNoUndoData {
            get {
                return ResourceManager.GetString("ErrorNoUndoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selection data is not formatted for this editor..
        /// </summary>
        internal static string ErrorSelectionDataInvalid {
            get {
                return ResourceManager.GetString("ErrorSelectionDataInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The two selections do not match in size..
        /// </summary>
        internal static string ErrorSelectionsMismatch {
            get {
                return ResourceManager.GetString("ErrorSelectionsMismatch", resourceCulture);
            }
        }
    }
}
