//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MushROMs.Editors.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Size8x")]
        public global::MushROMs.Editors.PaletteBGSize PaletteBGSize {
            get {
                return ((global::MushROMs.Editors.PaletteBGSize)(this["PaletteBGSize"]));
            }
            set {
                this["PaletteBGSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlLightLight")]
        public global::System.Drawing.Color PaletteBGColor1 {
            get {
                return ((global::System.Drawing.Color)(this["PaletteBGColor1"]));
            }
            set {
                this["PaletteBGColor1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ControlDarkDark")]
        public global::System.Drawing.Color PaletteBGColor2 {
            get {
                return ((global::System.Drawing.Color)(this["PaletteBGColor2"]));
            }
            set {
                this["PaletteBGColor2"] = value;
            }
        }
    }
}
